### PR TITLE
feat(filters): Add safari extensions to browser extension filter

### PR DESCRIPTION
**Pull request by lobsterkatie**
By popular request. Also adding it on the python side of things, in https://github.com/getsentry/sentry/pull/16304.

### CODE REVIEW

**Review by dashed — APPROVED** [review]
Looks good to me 👍

**Comment by dashed** [comment]
Ah. I just noticed this got merged.

-------

@jan-auer I hope my approval on this PR wasn't too premature. 😬 It looked fine to me. Can you do a pass on this to ensure it looks good to you?

**Comment by jan-auer** [comment]
All good, this was also discussed offline. 

I put code owners in place now to ensure that there’s at least one review from a team member. Please continue to review :)

**Comment by lobsterkatie** [comment]
Shoot, sorry, y'all. I thought it was kinda a 'mash approve' situation and went ahead with it. Seems like we're okay, but sorry if I jumped the gun!

**Pull request merged**
