### PR TITLE
ref(pii): Get rid of custom deserialize

### PR DESCRIPTION
**Pull request by untitaker**

### CODE REVIEW

**Review by jan-auer — COMMENTED** [review]
Looks good. What are the aliases for?

**Comment by untitaker** [comment]
@jan-auer we have a bug in the data scrubbing UI that I thought would be best fixed with aliases. I was under the assumption that we already had persisted broken PII configs. However, that's not actually true and we'll just fix the bug in the UI.

**Comment by untitaker** [comment]
See https://github.com/getsentry/sentry/pull/19478

**Review by jan-auer — APPROVED** [review]
There's still one alias, but I don't mind it.

**Comment by untitaker** [comment]
Yes, that alias has been there from the start though (RedactPairWithLegacy)

**Pull request merged**
