### PR TITLE
feat(spans): disable redis span metrics extraction

### PR DESCRIPTION
**Pull request by DominikB2014**
We originally re-enabled db.redis in order to collect metrics for the cache module. However, since then we decided that the cache module will only look at `cache.*` span ops.

Therefore we can stop collecting `db.redis` span metrics.

### CODE REVIEW

**Review by Dav1dde — COMMENTED** [review]
Should we also remove some of the redis spans from the `test_extract_span_metrics` test?

**Comment by DominikB2014** [comment]
> test_extract_span_metrics

Yes!

**Comment by DominikB2014** [comment]
> Should we also remove some of the redis spans from the `test_extract_span_metrics` test?

yes!

**Comment by DominikB2014** [comment]
>Should we also remove some of the redis spans from the test_extract_span_metrics test?

@Dav1dde I'm indifferent to this, I could see us needing the db.redis spans in the future, so I'm okay with keeping these spans in the tests, if we re-add them back we'll have something to test against. Also having them there does verify that the metrics are not indeed being extracted.

**Comment by Dav1dde** [comment]
Sounds good to me, I don't have an issue with keeping them around 👍

**Review by Dav1dde — APPROVED** [review]

**Pull request merged**
