### PR TITLE
Fix build error on the platforms where sentry-native is not being built

### PR DESCRIPTION
**Pull request by mkhon**
The error is:

```
error: couldn't read .../build/relay-crash-20eaf6600db2deb6/out/bindings.rs: No such file or directory (os error 2)
```

The problem is that bindings.rs is not generated on such platforms.

### Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

#skip-changelog

### CODE REVIEW

**Comment by iker-barriocanal** [comment]
Hi @mkhon, thanks for contributing! When is `sentry-native` not built? I've tried replicating the error by cloning the repo on an empty directory and just running `make` sets everything up for [setting up and running](https://github.com/getsentry/relay#building-and-running) Relay. Could you provide some more details of your setup?

**Comment by mkhon** [comment]
It is not built on unsupported platforms (not MacOS or Linux), but the relay on these platforms still can be built (and not generating bindings.rs is the only issue on such platforms)

**Comment by iker-barriocanal** [comment]
What platforms were you targeting? I wonder if it's worth adding them to the CI workflows too.

**Comment by mkhon** [comment]
We are building relay on FreeBSD (yuck!)

**Review by iker-barriocanal — APPROVED** [review]
LGTM! Could you add a changelog entry? See instructions in https://github.com/getsentry/relay#instructions-for-changelogs? Thanks for your contribution!

**Comment by iker-barriocanal** [comment]
Hi @mkhon, getting back to this. The compilation feature flag `crash-handler` decides whether sentry native is compiled, so disabling that feature flag should skip building that piece and thus not erroring. This is documented in the [README](https://github.com/getsentry/relay?tab=readme-ov-file#features). Let me know if you have any questions!

**Pull request closed without merging**
