### PR TITLE
build(uap-core): Bump to latest version

### PR DESCRIPTION
**Pull request by rhcarvalho**
There's been a handful of updates since Nov 8, 2019.

https://github.com/ua-parser/uap-core/compare/9db18c34f47ee8a30fcd1615ffcbb3ba4e02f287..ec8322ffe14f94d88131cec550705f392085a519

### CODE REVIEW

**Comment by rhcarvalho** [comment]
Build failure

https://travis-ci.com/github/getsentry/relay/jobs/299606102

```
$ make -e test-rust-all
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    20  100    20    0     0     87      0 --:--:-- --:--:-- --:--:--    87
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Makefile:206: recipe for target 'GeoLite2-City.mmdb' failed
make: *** [GeoLite2-City.mmdb] Error 2
```

I've seen the same make output locally when I tried to download `GeoLite2-City.mmdb`... and realized I don't have some env var with a key. Maybe download is failing with a key as well, if Travis has one.

**Comment by jan-auer** [comment]
Could you rebase onto or merge `master`? This should get the build green.

**Comment by rhcarvalho** [comment]
Rebased against latest master, see [comparison]( https://github.com/getsentry/relay/compare/4da8a9c6fe1382aace2c610ef4c4aadd5509ee73..310f94f3ddf2623de4086792daa527685e7e5611) (nothing in the content of this PR).

**Review by untitaker — APPROVED** [review]
This seems straightforward

**Comment by rhcarvalho** [comment]
As I thought it could, it does break a test though:

https://travis-ci.com/github/getsentry/relay/jobs/300417269#L1413-L1433

```
---- store::normalize::user_agent::tests::test_os_context_full_version stdout ----
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Snapshot Differences ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Snapshot: os_context_full_version
Source: relay-general/src/store/normalize/user_agent.rs:222
-old snapshot
+new results
────────────────────────────────────────────────────────────────────────────────
event.contexts
────────────┬───────────────────────────────────────────────────────────────────
    2     2 │   "client_os": {
    3     3 │     "name": "Mac OS X",
    4     4 │     "version": "10.13.4",
    5     5 │     "type": "os"
          6 │+  },
          7 │+  "device": {
          8 │+    "family": "Mac",
          9 │+    "model": "Mac",
         10 │+    "brand": "Apple",
         11 │+    "type": "device"
    6    12 │   }
    7    13 │ }
────────────┴───────────────────────────────────────────────────────────────────
```

Apparently the new code in the submodule adds more information. I could just update the test to include that.

Any concerns?

**Comment by untitaker** [comment]
That should be fine, after all it really only adds data.

**Comment by rhcarvalho** [comment]
Updated test to match new, increased, output based on new version of uap-core.

**Review by jan-auer — APPROVED** [review]
Excellent!

**Pull request merged**
