### PR TITLE
fix: Don't timeout when query is being slow

### PR DESCRIPTION
**Pull request by untitaker**
Actix' default timeout is one second, but that does not really help if
we, by default, wait 5 seconds for batching. Adjust timeout of SendQuery
to be a multiple of the batch_timeout.

### CODE REVIEW

**Comment by untitaker** [comment]
I wonder if we could change the batching instead such that the headers are already returned, but the body is still taking some time.

Technically this is already wrong because the upstream batch_timeout might be different from what the requesting relay has configured.

**Comment by jan-auer** [comment]
We should probably also just lower the batch timeout back to one second. I did not check actix timeouts, to be honest, but it doesn't make sense to wait so long for queries. I was wondering if it could make sense to introduce different timeouts for store vs. queries.

IMHO, the query timeout should not be tied to the batch timeout. As you said, upstream relays are not guaranteed to have the same configuration.

**Comment by untitaker** [comment]
Yeah but that doesn't mean it's better to have no correlation between them. If we don't make them correlate, the user will practically not be able to increase batch_timeout without making all queries timeout (rendering the config option useless)

**Comment by jan-auer** [comment]
Thinking about it again, this problem has several layers:
 1. For queries, we might want to answer as quickly as possible. If we have a timeout, it accumulates with a chain of relays -- thus, removing the timeout completely would be reasonable. 
 2. Self-hosted relays will however only query for a single project. In turn, our central relays will have to answer multiple project queries (with potentially one project each), so they will want to batch.

Maybe we should make batching optional. Store always batches. Queries only batch when enabled in configuration (off by default, for self-hosting).

And yes, I would say we should not correlate them, but rather have a separate setting or even hard-coded maximum. And we rather cap the batch_interval setting at that maximum to ensure that downstream relays can never timeout.

**Comment by untitaker** [comment]
I feel like there should be a way for upstream relays to communicate the expected delay to downstream. We can send the response headers before knowing the query results, so we should be able to send some information about the batching-incurred delay with them.

I see what you mean now, so this PR can't possibly work.

**Comment by untitaker** [comment]
An alternative would be to just make the client timeout configurable as well. Then we can pick any defaults we'd like without restricting custom config.

EDIT: you already said that

**Comment by mitsuhiko** [comment]
For what it's worth this feels a bit like a deja vu because that's the reason why queries originally could reply a pending and you had to poll for them again. Maybe we can end up with some sort of compromise where if a relay is interested in more than one project config it can indicate to the upstream to only return cache hits and it then fetches the missing ones again one by one or in smaller chunks.

**Comment by untitaker** [comment]
Too large requests are not the problem though, each of those chunks will take just as long as batch-timeout is large.

**Comment by mitsuhiko** [comment]
@untitaker it's not about the size but about not being able to take advantage of cache hits.

**Comment by untitaker** [comment]
Also I feel like this would exchange the question "how long do I wait" with "how often do I poll"

**Comment by mitsuhiko** [comment]
@untitaker I think the question is not "how long do i wait" but "how much do I block" and "whom do i block". Right now if there is one not cached item the entire chain is blocked and all items that were queried. Which means the first relay can't process any items.

If we can take advantage of cache hits we unblock all relays in the chain early for all cache hits and only hit the slow path that blocks the chain for the non cache hit cases.

**Comment by untitaker** [comment]
Ok, I think I understand now what you want to accomplish. Could we stream back the batches instead? I. E. one JSON object per item, so you can send out the cache hits immediately and keep the connection open if there are cache misses where the items will follow later.

```
{"id":..., "config" :...} \n
...
```

Basically this: http://jsonlines.org/

**Comment by mitsuhiko** [comment]
We could do that but the risk is that if someone puts another proxy in between that does not support response streaming we will be blocked anyways.

**Comment by untitaker** [comment]
Though to be honest I don't think it is important to unblock events as soon as possible and would rather only fix the problem this PR tries to solve. I'd much rather just fiddle with the timeout and batching settings like @jan-auer proposes

**Comment by jan-auer** [comment]
_Offline discussion with @untitaker:_ We'd propose to make two changes to the current behavior in master:

1. Make the upstream request timeout configurable. It will stay *5s* by default. This should allow users to increase it in case they really run into troubles
2. Decrease the default batch timeout to `100ms`. Sentry should be able to easily answer 10 queries per second from each of our inner relays. This should keep the overall delay very small, considering that people are not going to nest relays too much.

**Comment by jan-auer** [comment]
@mitsuhiko @untitaker This should be ready to merge now. I'll work on the rest we discussed in separate PRs.

**Review by jan-auer — APPROVED** [review]
Modulo my changes, gtg. Please reduce the timeouts, though.

**Pull request merged**
