### PR TITLE
test(pattern): Add tests for empty alternates

### PR DESCRIPTION
**Pull request by Dav1dde**
Born from #4277 

#skip-changelog

### CODE REVIEW

**Comment by loewenheim** [comment]
One slight wrinkle here is that `foo{}` matches `"foo"` but `{}` doesn't match `""`.

**Comment by Dav1dde** [comment]
> One slight wrinkle here is that foo{} matches "foo" but {} doesn't match "".

I think it's fine to reduce a `{}` glob to an empty glob, which has the explicit rule:

> The empty glob `""` never matches.

This PR doesn't change or mention the empty behaviour it just asserts some other cases.

**Comment by loewenheim** [comment]
Ah yeah, that makes sense actually. It does call the whole idea of #4277 into question, though—if the empty glob doesn't match anything, why does an empty alternative?

**Comment by Dav1dde** [comment]
> if the empty glob doesn't match anything, why does an empty alternative?

In my mind:
- `{,}` should be the same as `{}` which may be reduced away -> `{,}` is an empty glob.
- `{foo,}` is not an empty alternate, it's an optional `foo`.

**Comment by Dav1dde** [comment]
We can also explicitly implement an `Optional` token instead of smuggling into alternates with an empty literal. Which may reduce the confusion, we just don't have special syntax for this (except as an alternate).

`{foo,bar,}` -> `Optional(Alternate(Literal(foo), Literal(bar)))`

**Comment by loewenheim** [comment]
> We can also explicitly implement an `Optional` token instead of smuggling into alternates with an empty literal. Which may reduce the confusion, we just don't have special syntax for this (except as an alternate).

I'm in favor of this.

**Review by loewenheim — APPROVED** [review]

**Comment by Dav1dde** [comment]
Let's add an `Optional` token!

**Pull request merged**
