### PR TITLE
chore(deps): Update `terminal_size`

### PR DESCRIPTION
**Pull request by iambriccardo**
Update `terminal_size` to the latest one which also removes old versions `rustix` `linux-raw-sys` `errno`.

#skip-changelog

### CODE REVIEW

**Review by olksdr — CHANGES_REQUESTED** [review]
What is the reason for this update? 

Instead we might actually be able to update `terminal_size` which in return should bump `rustix` to `0.37.x`

**Comment by iambriccardo** [comment]
> What is the reason for this update?
> 
> Instead we might actually be able to update `terminal_size` which in return should bump `rustix` to `0.37.x`

Had a chat with Jan since I got `error[E0554]: #![feature] may not be used on the stable release channel` on my machine when compiling with the latest stable Rust version. So we tried to update and it works and he said that updating it should be good.

**Comment by olksdr** [comment]
Please, run 
```bash
> cargo update -p terminal_size
```

to update `terminal_size` instead and please, test it on your machine. And then also update this PR and we will merge the changes.

**Review by olksdr — APPROVED** [review]
lgtm

**Pull request merged**
