### PR TITLE
fix: Preserve event id of minidump upload

### PR DESCRIPTION
**Pull request by untitaker**

### CODE REVIEW

**Review by jan-auer — CHANGES_REQUESTED** [review]
Unfortunately, this is not sufficient. We also need to parse this from other payloads. Ideally, we would abstract over that, given that we already have this helper in another place. If I remember correctly, then there are the following ways to ingest an event ID with minidumps:

1. The `sentry` key containing a JSON-encoded payload
2. The `sentry[event_id]` key containing the event ID
3. The `__sentry-event` messagepack payload
4. If we want to support it going forward (did not support in the past), the `guid` form field
5. Random generated.

You can see these different extractions in `EventProcessor::extract_event`.

**Comment by untitaker** [comment]
>Ideally, we would abstract over that

yeah so this is where my confusion starts. We can abstract over it, but then we will probably just pay the cost of parsing everything twice... once in the endpoint and once in the event processing.

**Comment by jan-auer** [comment]
> we will probably just pay the cost of parsing everything twice

Most likely we have to do that :( 
Unfortunately, we cannot rely on the SDK to send the event id in a header.

**Comment by untitaker** [comment]
@jan-auer do you think we could get away with parsing the event ID only from a few select places and preventing it from being set in others? I.e. we allow `sentry[event_id]` in formdata but actually show an event error when it is being set through `__sentry_event` etc

**Comment by jan-auer** [comment]
Unfortunately, we have to support both the `sentry` JSON value and `__sentry-event`. I don’t think anyone ever sent `sentry[event_id]`, but it’s strange to have that as an exception tbh.

**Review by untitaker — COMMENTED** [review]
I approve

**Review by jan-auer — APPROVED** [review]
If @untitaker approves, I approve.

**Pull request merged**
