### PR TITLE
ref: Rename semaphore to Relay

### PR DESCRIPTION
**Pull request by jan-auer**
Renames Semaphore to Relay:
- All crates
- The binary
- The CABI
- Documentation refering to the library or binary
- The config folder name (`.relay`)

What is not renamed (yet):
- The GitHub repository: **next step**
- The docker container name (`us.gcr.io/sentryio/semaphore`)
- The python library

### CODE REVIEW

**Comment by dashed** [comment]
Finally 😄

**Comment by jan-auer** [comment]
Apart from cloudbuilder, everything is working again. However, I wasn't able to regenerate the C-header with `cbindgen` due to a build error.

**Review by untitaker — APPROVED** [review]

**Comment by untitaker** [comment]
@jan-auer what was the build error? missing ;?

**Comment by jan-auer** [comment]
> @jan-auer what was the build error? missing ;?

@untitaker exactly, have you encountered it? Initially I thought it happens due to my rust nightly not matching what cbindgen wants.

**Pull request merged**
