### PR TITLE
docs(readme): Remove onpremise notice

### PR DESCRIPTION
**Pull request by max-wittig**
on-premise already uses the latest relay

### CODE REVIEW

**Comment by jan-auer** [comment]
Thanks, we'll merge this as soon as we have an official release of `onpremise` with Relay.

**Review by jan-auer — APPROVED** [review]

**Comment by max-wittig** [comment]
Thanks @jan-auer. Are you sure that `onpremise` has releases? The last `onpremise` release was with 9.1.2?

**Comment by jan-auer** [comment]
> The last `onpremise` release was with 9.1.2?

The latest release is actually `10.0.0`, which you can find on Dockerhub (see [Versioning](https://github.com/getsentry/onpremise#versioning)). It's just not tagged as release on GitHub.

There will be another release in June 2020, with monthly releases following after.

**Comment by max-wittig** [comment]
@jan-auer Thanks for the info! We've switched to master because we were unsure how often releases are crafted and if there will be security patches etc. 

Good to know that there will be monthly releases coming! Thanks!

**Review by BYK — APPROVED** [review]

**Comment by jan-auer** [comment]
Version `20.6.0` has been released today! 🚀

**Pull request merged**
