### PR TITLE
fix(spans): Scrub integer file extensions

### PR DESCRIPTION
**Pull request by jjbayer**
We've seen resource span descriptions like `http://domain.com/*.123` which cause high cardinality in the extension.

#skip-changelog

### CODE REVIEW

**Review by DominikB2014 — APPROVED** [review]

**Review by Dav1dde — APPROVED** [review]
Maybe we should just have a whitelist of extensions instead?

**Comment by jjbayer** [comment]
> Maybe we should just have a whitelist of extensions instead?

@Dav1dde That's a good point. @DominikB2014 would the list of supported images be short enough to enumerate?

**Comment by DominikB2014** [comment]
> > Maybe we should just have a whitelist of extensions instead?
> 
> 
> 
> @Dav1dde That's a good point. @DominikB2014 would the list of supported images be short enough to enumerate?

We do have a list of extensions that we look for in the FE

https://github.com/getsentry/sentry/blob/master/static/app/views/performance/browser/resources/shared/constants.ts

This mostly lines up with

https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Image_types

But I'm not sure if this includes all types tho. Are we able to query for all extensions that we have seen to be sure?

**Comment by jjbayer** [comment]
> But I'm not sure if this includes all types tho. Are we able to query for all extensions that we have seen to be sure?

@DominikB2014 I ran a query and posted the results [here](https://www.notion.so/sentry/Allowlist-for-file-extensions-65ce495452cc42f3be69062c7b6a47fa?pvs=4#df3c6dc55f8f478e830e631ca936738e), let me know which of those you would like to add to the allowlist!

**Pull request merged**
