### PR TITLE
ref(actix): Migrate the AwsExtension to tokio

### PR DESCRIPTION
**Pull request by jan-auer**
Plain migration of the AWS extension. On error and on shutdown, the extension
stops as before. Since the extension is fully asynchronous, it can run on the
main runtime.

#skip-changelog

### CODE REVIEW

**Comment by jan-auer** [comment]
@sl0thentr0py or @antonpirker, could you please confirm that the behavior of the extension on error is desired? We can now also make it retry.

**Comment by jan-auer** [comment]
I will push a fixes for CI in a bit (networking troubles).

**Comment by sl0thentr0py** [comment]
thx @jan-auer, I tested behavior with my mock service as well, lgtm and also much cleaner without the explicit runtime!

The error case is the same as before and I think that's fine.
We could in principle retry if `next_event` fails, but that could lead to a hot loop without a sleep or something and the duration of that sleep is a fairly hacky decision. Let's just leave it for the future.

**Review by sl0thentr0py — APPROVED** [review]

**Review by olksdr — APPROVED** [review]
:shipit:

**Pull request merged**
