### PR TITLE
build: Update schemars and remove workarounds

### PR DESCRIPTION
**Pull request by jan-auer**
#skip-changelog

### CODE REVIEW

**Comment by jan-auer** [comment]
@untitaker FYI: schemars is adding `additionalProperties: false` in some cases now, which makes some events fail schema validation. Still have to investigate why that happens.

**Comment by untitaker** [comment]
I've updated the schema snapshot and removed the offending tests instead of removing additionalProperties. The goal was to document the canonical schema that SDKs should send, and that was never what the test that I wedged the jsonschema assertions into was about. In particular it threw because the StoreProcessor added event errors, which we do want to test in that particular position.

My reasoning for keeping additionalProperties: false is that SDKs should not send additional properties, even if doing so would not cause the server to drop the event. But then, most type violations are fine by that standard. The intermediate goal was to have something that the SDKs could use to validate their input, especially against property typos. having `additionalProperties: true` would basically not catch typos like `logetrny` since that attribute (and a lot of attributes in general) are optional.

**Comment by jan-auer** [comment]
Thanks, @untitaker. In this case, we should not treat this as the event payload schema -- used for validating inbound payloads and documented for SDK developers -- but rather call it out as the internal schema after final store normalization. We will also need to remove certain structures from the JSON schema in this case, as the store normalizer always removes them.

**Comment by untitaker** [comment]
The schema is the canonical schema the sdks should send, it's not the one
after store normalization

**Pull request merged**
