### PR TITLE
fix: Trim on renormalization

### PR DESCRIPTION
**Pull request by untitaker**
Trimming twice is generally suboptimal, but useful to avoid issues when
loading old events or events that have been bloated by stacktrace
processors.

Full disclosure, we don't have data that this is actually an issue in practice.

### CODE REVIEW

**Comment by mitsuhiko** [comment]
For what it's worth i think this is at least partially consistent with what we do in the python code path.

**Review by mitsuhiko — APPROVED** [review]

**Comment by untitaker** [comment]
Yes, but I think the consensus at some point was that trimming twice is weird.

**Comment by mitsuhiko** [comment]
On second though i think we should test this. I'm not sure if we apply the same rules here.

**Comment by untitaker** [comment]
@mitsuhiko Are you concerned about multiple trimming annotations or something like that?

**Comment by mitsuhiko** [comment]
Also that we trim harder than we do in the python code on re-reading

**Comment by mitsuhiko** [comment]
Some of these values go into the grouping algorithm for instance.

**Pull request merged**
