### PR TITLE
instr: Run filter_event 2x to catch normalization bugs [ISSUE-1574]

### PR DESCRIPTION
**Pull request by jjbayer**
As reported in https://getsentry.atlassian.net/browse/ISSUE-1574, browser extension filters seem to have stopped working in certain cases after we moved event filtering _before_ full store normalization.

To make sure we catch all cases where filtering fails because light normalization does not cover everything it needs, run `filter_event` again after full store normalization, and log an error if the event would now be filtered.

#skip-changelog

### CODE REVIEW

**Review by flub — COMMENTED** [review]
this is not just in test code but will happen for all envelopes processed, right?  Should this be ever turned off again to save resources or is this to stay forever to catch future bugs as well?

**Comment by jjbayer** [comment]
> this is not just in test code but will happen for all envelopes processed, right? Should this be ever turned off again to save resources or is this to stay forever to catch future bugs as well?

@flub This is intended as a short-term change which we can revert once we are confident that filtering works as well as it did before the light normalization change. @jan-auer even suggested to not merge this, and only deploy to canary, which I think is a good idea.

**Comment by jjbayer** [comment]
Ran this on Canary, have enough data for now. Will reopen the PR if needed.

**Comment by iker-barriocanal** [comment]
Reopening to rerun the experiment.

**Comment by iker-barriocanal** [comment]
Closing because the experiment finished.

**Pull request closed without merging**
