### PR TITLE
fix(py): Allow None in is_glob_match

### PR DESCRIPTION
**Pull request by jan-auer**
Ref https://github.com/getsentry/sentry/pull/15441

### CODE REVIEW

**Comment by untitaker** [comment]
To me it doesn't make sense to call the function with `None`. It seems to be an accident that it works with the stdlib version, as fnmatch in python does not document what should happen on None

**Comment by jan-auer** [comment]
Good point, but since we’re using this as a drop-in replacement we should stay compatible. Who knows where else we are passing None

**Comment by mitsuhiko** [comment]
```python
>>> fnmatch.fnmatch(None, '*.py')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python@2/2.7.16_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/fnmatch.py", line 43, in fnmatch
    return fnmatchcase(name, pat)
  File "/usr/local/Cellar/python@2/2.7.16_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/fnmatch.py", line 83, in fnmatchcase
    return re_pat.match(name) is not None
TypeError: expected string or buffer
```

How does that make sense?

**Comment by jan-auer** [comment]
Shame on me, I didn’t verify. Closing

**Pull request closed without merging**
