### PR TITLE
ref: Use jemalloc instead of system allocator

### PR DESCRIPTION
**Pull request by untitaker**
I hope that this will improve memory usage

### CODE REVIEW

**Review by bruno-garcia — APPROVED** [review]

**Review by mitsuhiko — APPROVED** [review]

**Review by jan-auer — COMMENTED** [review]
Can we test perf differences before merging please?

**Comment by untitaker** [comment]
@jan-auer I benched locally and could not see any difference at all. My suspicion is that this will have a positive impact on memory fragmentation at best.

**Comment by jan-auer** [comment]
If there was no measurable difference, why were we merging this then?

**Comment by untitaker** [comment]
Because I tested rps, nothing else. That gives me some confidence that it
does not break or heavily regress semaphore in perf, but it is yet to be
seen if it maybe improves memory usage of long running instances.

**Pull request merged**
