### PR TITLE
[WIP] fix: Remove debug information from release builds

### PR DESCRIPTION
**Pull request by tonyo**

### CODE REVIEW

**Comment by tonyo** [comment]
@mitsuhiko I guess we don't really need that `debug = true`?

**Comment by jan-auer** [comment]
Without that, stack traces are not quite as usable. I am wondering though why build times are that high to begin with.

**Comment by tonyo** [comment]
Is there a chance that we hit one of these?
https://github.com/rust-lang/rust/issues/49402
https://github.com/rust-lang/rust/issues/49467
For some reason we've witnessed build failures only for i686 so far.

**Comment by mitsuhiko** [comment]
I really want to keep debug info for release builds. I don't think we hit either of the cases linked.

**Comment by tonyo** [comment]
I can locally reproduce the build failure for i686 with current (1.26.2) and nightly Rust. I suggest to disable those 32-bit builds (for both Linux and Windows) temporarily, so we're not fully blocked by this.

**Comment by mitsuhiko** [comment]
Closing this. We want to keep debug info

**Pull request closed without merging**
