### PR TITLE
feat(pii): Quoted keys in selectors

### PR DESCRIPTION
**Pull request by untitaker**
Besides the fact that this is probably something the user wants (ability to address keys with whitespace etc in them), we need this to safely roundtrip PII configs generated from legacy datascrubber settings, where all kinds of keys are possible. We would previously emit PII configs that are broken.

Relay-as-store is not affected by this bug, python store is though.

### CODE REVIEW

**Review by jan-auer — APPROVED** [review]
WFM, I guess, but I wonder why not go with usual `\\` escaping?

**Comment by untitaker** [comment]
I didn't want to implement any escape sequences at all. This is very similar to how single quotes work in bash. Almost every character is literal:

```
$ echo '\'
\

$ echo '\xef'
\xef
```

Where it falls apart is when you want to select a key with a literal `'` in it. I don't think such keys exist, but I think it means we should reconsider this design. I thought I could just punt on it and eventually introduce separate syntax with double-quotes and escape sequences. This would be somewhat silly but at the same time still exactly how bash works, so at least not that outlandish or "foreign"

BTW slightly unrelated, I am intending on making `foo.*bar*` work too, but with wildcards only working at the beginning and end of the string. If you wanted to match on spaces the syntax would become `foo.*'bar baz'*`

**Comment by untitaker** [comment]
Actually I think I have no better idea. New syntax for escaping single quotes:

```
foo.'bar''baz'.bam
```

is selecting `{"foo": {"bar'baz": {"bam": ...}}}`

**Comment by untitaker** [comment]
@jan-auer can you re-review this one if you have time?

**Review by jan-auer — APPROVED** [review]

**Pull request merged**
