### PR TITLE
feat(webvitals): Adds Google Chrome to the list of allowed browser name tags for extracting inp metrics from spans

### PR DESCRIPTION
**Pull request by edwardgou-sentry**
Adds "Google Chrome" to the list of allowed browser name tags for extracting inp metrics from spans. This is required because the extracted browser name using client hints is "Google Chrome" for chrome browsers.

#skip-changelog

### CODE REVIEW

**Comment by edwardgou-sentry** [comment]
Chrome browser names for transactions is just "Chrome". Alternatively we can map "Google Chrome" to "Chrome" when parsing the user agent for browser name, but I feel like that would be more messy.

**Review by Dav1dde — APPROVED** [review]
I am curious where this difference between `Chrome` and `Google Chrome` is coming from (Chromium vs Google Chrome?) and wether it would make sense to unify them. 

Looking a bit through the code base, we already have `Google Chrome` elsewhere, unifying seems out of scope for now.

**Review by TBS1996 — APPROVED** [review]

**Review by iker-barriocanal — COMMENTED** [review]
I'd look into normalizing "Google Chrome" to "Chrome" instead, as this also provides some indirect benefits (e.g. reduced cardinality in these fields). Is there any reason to not normalize the name, from the product pov?

**Comment by edwardgou-sentry** [comment]
> I'd look into normalizing "Google Chrome" to "Chrome" instead, as this also provides some indirect benefits (e.g. reduced cardinality in these fields). Is there any reason to not normalize the name, from the product pov?

I don't think there is currently a product reason to have to use `Google Chrome`, but it feels more correct to me since that's the actual value that comes from the client hints. I don't have anything against normalizing to `Chrome` though.

I didn't look at how `browser.name` is generated for Transactions, but it seems to be done differently (because it's a different value). If we're abandoning Transactions in the future in favour of spans, maybe it makes sense to stick to the `Google Chrome` value from client hints, and then `Chrome` will naturally disappear? This might not be true or happen quickly though, because there could be existing Transaction product areas that rely on the browser name being `Chrome`.

@iker-barriocanal lmk if you think this is a blocker for this pr. I just wanted to add this in since it's blocking some of the work im doing with webvitals

**Review by DominikB2014 — APPROVED** [review]

**Review by iker-barriocanal — APPROVED** [review]
Thanks for the context @edwardgou-sentry! Not blocking. I'm not sure what it'll look like with only spans, but this aggregation improvement could have a nice positive impact.

Thanks for jumping and opening the PR too!

**Pull request merged**
