### PR TITLE
ci(docs): Check doc comments in CI

### PR DESCRIPTION
**Pull request by flub**
This fixes up all the doc comments and makes sure to add a check for
them in CI.

hello danger bot! nice to meet you here too:
#skip-changelog

### CODE REVIEW

**Review by untitaker — APPROVED** [review]

**Comment by flub** [comment]
There's one failure still where rustdoc claims that there's a reference to a private item in a public item.  I'm completely baffled by that: the referenced item is public as far as I can see.  Any hints appreciated.

**Review by jan-auer — DISMISSED** [review]
Rather than doing this, I would opt to make more doc comments public. We already have a job that checks public doc comments.

**Comment by untitaker** [comment]
I do think this is fine, we shouldn't couple API design and stability to which doc comments are validated for correctness. We do now check doc comments twice, so perhaps we can just skip doc comments in the other job.

**Comment by jan-auer** [comment]
Going back on my previous comment, you're right. Let's move forward with this.

The remaining failure is a false-positive. There's a public field _and_ a private function of the same name, which is not too uncommon. Documentation for this is generated correctly, it's just the warning that triggers. You could avoid that by renaming the private function to something similar.

**Comment by flub** [comment]
> Rather than doing this, I would opt to make more doc comments public.

I agree with Markus here, if you'd like to do that, please go ahead.  This is still useful independently though.

> We already have a job that checks public doc comments.

Ooh, this is hidden in the "deploy" workflow.  I did not find it there.  Plus it only uses `-Dbroken_intra_doc_links` rather than `-Dwarnings`.  I think it probably makes sense to keep this under the lint jobs as well with `--document-private-items`.

**Comment by flub** [comment]
> The remaining failure is a false-positive. There's a public field _and_ a private function of the same name, which is not too uncommon. Documentation for this is generated correctly, it's just the warning that triggers. You could avoid that by renaming the private function to something similar.

Doh, great spot.  Thanks!

**Comment by flub** [comment]
> We do now check doc comments twice, so perhaps we can just skip doc comments in the other job.

I'm going to leave it since it has it's own way of invoking the docs check and just in case they're different or diverge it would be really annoying if suddenly the docs build on master no longer passes without us getting a CI failure in a PR.

**Comment by untitaker** [comment]
ok. this is extremely tangential, but the reason I am suggesting this is because https://nexte.st/ is 1) supposedly a much faster testrunner 2) doesn't support doctests

so if doctests are their own separate job it would make it more feasible to try that out

**Comment by flub** [comment]
> ok. this is extremely tangential, but the reason I am suggesting this is because https://nexte.st/ is 1) supposedly a much faster testrunner 2) doesn't support doctests
> 
> so if doctests are their own separate job it would make it more feasible to try that out

none of this is about doctests though?

**Comment by untitaker** [comment]
oh right, nevermind!!

**Pull request merged**
