### PR TITLE
Update sentry-kafka-schemas to latest version

### PR DESCRIPTION
**Pull request by cmanallen**
#skip-changelog

### CODE REVIEW

**Review by untitaker — APPROVED** [review]

**Review by Dav1dde — COMMENTED** [review]
Seems like the patch version bump contains a breaking change and it compiles the schema now (which it didn't before). It looks like we can just use `Option<Schema>` instead of `Option<JSONSchema>` in Relay now.

Also please update the title of the PR to follow the git commit guidelines, it's too easy to forget changing the commit message when merging otherwise.

**Comment by cmanallen** [comment]
@Dav1dde Can you link me to the commit guidelines?  Google is not helping me :D

**Comment by Dav1dde** [comment]
@cmanallen These ones https://develop.sentry.dev/commit-messages/

**Comment by Dav1dde** [comment]
Updated in #3305

**Pull request closed without merging**
