### PR TITLE
chore(toolchain): Migrate to 2021 edition

### PR DESCRIPTION
**Pull request by olksdr**
With these changes the code migrates  to [`2021` edition](https://doc.rust-lang.org/edition-guide/rust-2021/index.html).

### CODE REVIEW

**Review by jjbayer — APPROVED** [review]
Did you follow https://doc.rust-lang.org/cargo/commands/cargo-fix.html#edition-migration?

I would argue this is worth a changelog entry (under "Internal").

**Review by flub — APPROVED** [review]

**Comment by olksdr** [comment]
> Did you follow https://doc.rust-lang.org/cargo/commands/cargo-fix.html#edition-migration?

@jjbayer  Yeah, and basically  few changes I had to do to make the lint and tests work.  


> I would argue this is worth a changelog entry (under "Internal").

I will add the entry 👍

**Review by sl0thentr0py — APPROVED** [review]

**Review by jan-auer — APPROVED** [review]

**Comment by olksdr** [comment]
@jjbayer  Added the changelog entry in [bcc6adf](https://github.com/getsentry/relay/pull/1510/commits/bcc6adf601d10ddccfa445d9f4fcc9195f52a706).

**Comment by jjbayer** [comment]
> @jjbayer Added the changelog entry in [bcc6adf](https://github.com/getsentry/relay/pull/1510/commits/bcc6adf601d10ddccfa445d9f4fcc9195f52a706).

Cool, thanks!

**Review by viglia — APPROVED** [review]

**Pull request merged**
