### PR TITLE
Always print memory usage from readiness probe

### PR DESCRIPTION
**Pull request by beezz**
For debugging purposes, always log memory usage from the readiness probe.

### Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

### CODE REVIEW

**Comment by Dav1dde** [comment]
@beezz should we have a distribution metric instead?

**Comment by beezz** [comment]
> @beezz should we have a distribution metric instead?

I did not mean to merge it like this, just to run it for a few tests but the distribution metric sounds much better 👍

**Comment by Dav1dde** [comment]
> I did not mean to merge it like this, just to run it for a few tests

Ah I forgot you have OPS powers and can do that 👍

**Comment by Dav1dde** [comment]
Closing this now, think this is no longer needed and we have metrics emitted from Relay now.

**Pull request closed without merging**
