### PR TITLE
fix(pii): Rewrite selector specificity to be much more lenient

### PR DESCRIPTION
**Pull request by untitaker**
This fixes a bug where OR-ing a specific selector with `**` would make it non-specific. This should not be the case universally, the selector should continue to be specific if the specific sub-selector matches.

The PII benchmarks are regressing by 10% on average, so that's alarming. Let's be careful when rolling this out...

The final behavior for selectors is:
- `foo` matches on a field "foo" if it is either `Pii::True` or `Pii::Maybe`.
- `foo.*` matches on fields in "foo" that are either `Pii::True` or `Pii::Maybe`.
- `foo.**` matches recursively on fields in "foo"that are `Pii::True`.
- `$object` matches any object that is `Pii::True`.
- `$object.*` matches on fields in any object that are `Pii::True` (inherited from the `$object` specificity)

Inverted, the above rules mean:
- Fields with `Pii::True` are matched by all rules.
- Fields with `Pii::Maybe` not matched by `**`, unspecific `$`, or their descendants. All other rules match.
- Fields with `Pii::False` is never matched.

The final behavior for combinations is:
- `a || b` matches if any of the selectors matches based on the above rules
- `a && b` matches if all of the selectors match based on the above rules
- `!(a)` matches if and only if a does not match

### CODE REVIEW

**Comment by jan-auer** [comment]
Moving to draft state and waiting for a customer use case. This is generally fine, although we may want to use different naming for the enums.

**Comment by untitaker** [comment]
We have a customer case now, it looks like this:

```
** || culprit || $string || $frame.module || $frame.abs_path
```

culprit is not matched here although clearly it should be.

**Comment by jan-auer** [comment]
We discussed offline that @untitaker will attempt to simplify this without a tri-state.

**Comment by untitaker** [comment]
cont. https://github.com/getsentry/relay/pull/932

**Pull request closed without merging**
