### PR TITLE
test: Add a test for negative glob matches

### PR DESCRIPTION
**Pull request by untitaker**
see also https://github.com/getsentry/sentry-docs/pull/5336

#skip-changelog

### CODE REVIEW

**Review by jjbayer — APPROVED** [review]

**Review by iker-barriocanal — COMMENTED** [review]
From the [docs PR](https://github.com/getsentry/sentry-docs/pull/5336):

> `!` works for negation, but only within brackets

How does/should it behave when the negation is outside the square brackets?

**Comment by untitaker** [comment]
>How does/should it behave when the negation is outside the square brackets?

we currently don't support it, so it would be matched literally.

**Comment by iker-barriocanal** [comment]
I think it'd be valuable to have a unit test to know what the expected behavior of the negation outside square brackets is -- IMO it's easier to look at a unit test of 2 lines over looking at the code, in most cases. That said, consider this as a nice-to-have, and feel free to merge as-is.

**Comment by untitaker** [comment]
@iker-barriocanal yeah i just added one

**Review by iker-barriocanal — APPROVED** [review]

**Pull request merged**
