### PR TITLE
feat(web-vitals): add support for mobile browsers

### PR DESCRIPTION
**Pull request by KevinL10**
Adds support for mobile browsers to start ingesting web vitals. 

Continuation of https://github.com/getsentry/sentry/pull/73298/ which adds the scoring percentile configuration for mobile browsers.

### CODE REVIEW

**Comment by Dav1dde** [comment]
I wonder if we should normalize the mobile browsers instead 🤔 .

**Comment by KevinL10** [comment]
We could normalize `browser.name` but we still need a way to distinguish mobile browsers from desktop browsers since they have different scoring configurations. If we add a new tag it might be confusing for people who use span search and are already filtering by specific `browser.name` types like `Chrome Mobile`.

**Review by edwardgou-sentry — APPROVED** [review]
I think these browser names are set by relay by checking the user agent?
Normalizing these browser name sounds like it could be a different pr.

I think this change looks fine to unblock testing mobile perf scores for now.

**Review by iker-barriocanal — APPROVED** [review]

**Comment by iker-barriocanal** [comment]
> I think these browser names are set by relay by checking the user agent?

I'm ok with merging as-is, but a test to validate that would be great.

**Review by Dav1dde — APPROVED** [review]

**Pull request merged**
