### PR TITLE
ref(store): Emit event errors for unknown breadcrumb keys

### PR DESCRIPTION
**Pull request by jan-auer**
Emits normalization errors and event errors for unknown attributes in breadcrumbs.

See discussion on https://github.com/getsentry/sentry-python/pull/884#issuecomment-713682192.

### CODE REVIEW

**Comment by jan-auer** [comment]
I'm not so happy about the code duplication between `process_event` and `process_breadcrumb`, but it's surprisingly hard to factor out the common bits into a function, and makes everything more complicated than duplicating code.

**Comment by lobsterkatie** [comment]
Thanks, @jan-auer!

**Review by untitaker — APPROVED** [review]
You can probably use `before_process`, `after_process` or `process_other` and have customized logic in there (matching on path or value type) to factor out the logic. However I think this is cleaner.

In fact `process_other` was introduced for this purpose IIRC.

**Comment by jan-auer** [comment]
> In fact process_other was introduced for this purpose IIRC.

Correct.

> You can probably use `before_process`, `after_process` or `process_other` and have customized logic in there (matching on path or value type) to factor out the logic. However I think this is cleaner.

Not sure how that works, since we'd need a `before_process_breadcrumb` etc. Actually, the only thing we need is a method generic over `V: ProcessValue`, but I didn't feel it was worth the complications.

**Pull request merged**
