### PR TITLE
ref(metrics): Flatten AggregatorServiceConfig

### PR DESCRIPTION
**Pull request by TBS1996**
Prior to splitting the aggregatorservice with the aggregator we had just one big config. After we split it, we also split the config to reflect the service and hte aggregator, where the service config was just the aggregatorconfig flattened together with the values related to the service.

This nested structure, while it makes more sense in the implementation, made it harder to configure. This PR therefore 'unflattens' the service config so it looks as it did in the past. We keep the config for the inner aggregator and simply implement a `From<&aggregatorserviceconfig> for aggregatorconfig` in order to keep some of the implementation benefits of separation.  
 
The only downside is that it's less 'dry'. The values for inner aggregator is now present in both the serviecconfig and the inner config, so thats something we have to keep in mind in the future if we add new values. 

#skip-changelog

### CODE REVIEW

**Review by jjbayer — COMMENTED** [review]
I ran `make doc-rust` and the resulting docs look good to me! @TBS1996 could you also remove the doc comment that says "Only public for benchmarks", and add a doc comment to the module file itself instead, something like 

```rust
//! Core functionality of metrics aggregation.
```

**Comment by TBS1996** [comment]
yup, done!

**Review by jjbayer — APPROVED** [review]
LGTM, please ask @jan-auer if he wants to have another look.

**Review by jan-auer — APPROVED** [review]
LGTM. 

The docs for `Aggregator` still reside on `AggregatorService`. It would be good to move them, so that the module-level links point at a documented interface.

**Pull request merged**
