### PR TITLE
feat: Refactor build pipeline for Linux

### PR DESCRIPTION
**Pull request by tonyo**
This PR updates the build pipeline in a way that allows to cache the Docker image with build environment (specified by `Dockerfile.build`). I cannot think of a good way to take advantage of multi-staged builds, but performance-wise this approach is basically the same.

Also: basic smoke tests for compiled binaries.

### CODE REVIEW

**Comment by tonyo** [comment]
This should be ready now.

**Comment by tonyo** [comment]
@mitsuhiko Anything more advanced (check-wise) we could add here?

**Comment by mitsuhiko** [comment]
I'm more than okay with just this for now. In the ideal case we can actually run a sourcemap upload but that requires some fixtures.

**Comment by tonyo** [comment]
@mitsuhiko ehmm, sourcemap upload? Just to make sure, this is `semaphore`, not `sentry-cli`

**Comment by mitsuhiko** [comment]
Oh sorry I thought I replied to https://github.com/getsentry/sentry-cli/pull/358

**Comment by mitsuhiko** [comment]
I think we could send a dummy event through the normalization command and assert the output:

```
$ echo '{"message": "Hello World!", "fingerprint":[42]}' | semaphore process-event
{"fingerprint":["42"],"message":"Hello World!"}
```

**Comment by tonyo** [comment]
@mitsuhiko updated!

**Pull request merged**
