### PR TITLE
feat: Add basic envrc

### PR DESCRIPTION
**Pull request by untitaker**
It seems like direnv is our go-to approach for enabling virtualenvs automatically: sentry, snuba, ops repos have an envrc that does basically that.

#skip-changelog

### CODE REVIEW

**Review by flub — COMMENTED** [review]
it like, just shouts at you and that's it?  seems a bit needless to me

**Comment by untitaker** [comment]
@flub it activates the virtualenv. for comparison: https://github.com/getsentry/snuba/blob/430763e67e30957c89126e62127e34051eb52fd6/.envrc#L1-L13

this one installs the venv but i don't think we want something like that to happen on `cd`.

**Comment by flub** [comment]
oh, of course.  silly me

**Review by flub — APPROVED** [review]

**Comment by untitaker** [comment]
yeah so basically we use direnv like virtualenvwrapper. we can assume it is already installed because it is necessary-ish for sentry.

**Pull request merged**
