### PR TITLE
build: Prepare for CalVer releases

### PR DESCRIPTION
**Pull request by jan-auer**
Separates the Relay application binary from the library used by Sentry:

- **Relay binary** is released from the root folder. Run `craft prepare` and `craft publish` in that directory to create a release build and publish it, respectively. We use [Calendar Versioning](https://calver.org/) and coordinate releases with Sentry.

- **Relay Python library** along with the C-ABI are released from the `py/` subfolder. Change into that directory and run `craft prepare` and `craft publish`. We use [Semantic Versioning](https://semver.org/) and release during the development cycle.

Craft configuration, changelogs and builds are fully separated so that releases can run independently.

Requires https://github.com/getsentry/craft/pull/86

### CODE REVIEW

**Comment by jan-auer** [comment]
See these two branches for example builds:

- Binary release: https://github.com/getsentry/relay/compare/build/calver...release/20.5.0
- Library release: https://github.com/getsentry/relay/compare/build/calver...release-library/0.5.10

**Comment by jan-auer** [comment]
@BYK I just now noticed that Cargo enforces SemVer and doesn't allow leading zeros in version numbers. We have two options:

1. Switch to CalVer representation `0Y.MM.MICRO`, for example `20.5.0`. This would keep the version consistent between the binary and the tag.
2. Tag and publish with a leading zero, but omit it from the crate. That means, that the zero will be missing when running `relay --version` and from error reports sent to Sentry (internally).

The second option would require the following update in the `bump-version.sh` script:

```bash
NEW_VERSION="$(echo \"${2}\" | sed -e 's/\.0\([1-9]\)/.\1/')"
```

**Comment by BYK** [comment]
Let's go with calver-0Y.MM.MICRO as you suggested in option 1.

**Review by BYK — COMMENTED** [review]
LGTM

Does `craft` handle pushing to Docker Hub?

**Review by BYK — APPROVED** [review]

**Comment by jan-auer** [comment]
> Does `craft` handle pushing to Docker Hub?

@BYK good point. At the moment we push from GCB:

https://github.com/getsentry/relay/blob/1f0d5f8fab5fb64c4d882a001853ed5bdbaf1759/cloudbuild.yaml#L71-L76

I think this will need an additional tag on top of the existing image/tag in craft, which is not possible yet, afaik. Would you like to contribute a `docker` target to craft that tags?

**Comment by BYK** [comment]
>I think this will need an additional tag on top of the existing image/tag in craft, which is not possible yet, afaik. Would you like to contribute a docker target to craft that tags?

I'd rather stick to GCB for this and update the cloudbuild file but will also see about craft :)

**Review by untitaker — APPROVED** [review]

**Pull request merged**
