### PR TITLE
ref(crons): Rename DataCategory::MONITOR -> DataCategory::MonitorCheckIn

### PR DESCRIPTION
**Pull request by evanpurkhiser**
Before we start using this everywhere let's fix this naming so we don't
have to deal with this being confusing for the rest of time.

#skip-changelog

### CODE REVIEW

**Comment by evanpurkhiser** [comment]
This would be a breaking change for the exported python library. AFAICT we haven't used it at all yet in sentry.

I think it would be good to get this in before we actually start using it

**Comment by rjo100** [comment]
Need to update this as well?
https://github.com/getsentry/relay/blob/master/py/sentry_relay/consts.py

**Comment by evanpurkhiser** [comment]
Good call out. This appears to be auto-generated. Will have to figure out what's going on here

**Comment by evanpurkhiser** [comment]
I think this would be a breaking change for https://develop.sentry.dev/sdk/rate-limiting/ as well.

We would need to return both `monitor` and `monitor_checkin` when we rate-limit them.

**Comment by evanpurkhiser** [comment]
Going to leave this open, but I think it's unlikely we'll change this right now.

**Comment by evanpurkhiser** [comment]
@jan-auer could you comment on if changing this is feasible or even worthwhile? Maybe the naming change isn't necessary.

**Comment by evanpurkhiser** [comment]
Closing for now. May revisit in the future.

**Pull request closed without merging**
