### PR TITLE
feat: Add transaction event type

### PR DESCRIPTION
**Pull request by untitaker**

### CODE REVIEW

**Review by mitsuhiko — APPROVED** [review]

**Comment by mitsuhiko** [comment]
Why do we not want to set the other types?

**Review by jan-auer — APPROVED** [review]

**Comment by untitaker** [comment]
@mitsuhiko Didn't want to touch that now. I guess we could allow SDKs to set the other types?

**Comment by mitsuhiko** [comment]
@untitaker pretty sure this is a regression. I could swear SDKs were allowed to set the event type before rust normalization.

**Comment by mitsuhiko** [comment]
I just checked the old implementation and the comment said that SDKs should be able to set it (at least that's my reading) but it never actually permitted it.

https://github.com/getsentry/sentry/blob/32b3d144416dd5af870267c6ee8fe37eade6c016/src/sentry/event_manager.py#L468-L471

**Pull request merged**
